/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: daniel (https://sketchfab.com/enviromaster)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/chinese-money-plant-c571361c0ce34dfbb25c296cb6aad152
title: Chinese Money Plant
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

import { FMOscillator, FMSynth } from "tone";



export default function Plant({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('./chinese_money_plant/plant.gltf')



  const triggerSound = () => {
    const fmSynth = new FMSynth({}).toDestination()

    fmSynth.harmonicity.value = Math.random(.6, .8)
    fmSynth.harmonicity.detune = Math.random(0, 1)




    fmSynth.triggerAttackRelease('C5', '16n')
  }
  return (
    <group ref={group} {...props} dispose={null}>

      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Object_3.geometry} material={materials['Material.002']} onClick={triggerSound} />
        <lineSegments geometry={nodes.Object_4.geometry} material={materials['Material.004']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('./chinese_money_plant/plant.gltf')
